//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuLauncher.LangString {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YuLauncher.LangString.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationLog.
        /// </summary>
        public static string AppLogButton {
            get {
                return ResourceManager.GetString("AppLogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteGame {
            get {
                return ResourceManager.GetString("DeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to edit mode.
        /// </summary>
        public static string EditModeButton {
            get {
                return ResourceManager.GetString("EditModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Pick FilePath.
        /// </summary>
        public static string ErrPickPath {
            get {
                return ResourceManager.GetString("ErrPickPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension: .
        /// </summary>
        public static string ExtensionLabel {
            get {
                return ResourceManager.GetString("ExtensionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FavGames.
        /// </summary>
        public static string FavoriteGame {
            get {
                return ResourceManager.GetString("FavoriteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file type is cant open.
        /// </summary>
        public static string FileCantOpen {
            get {
                return ResourceManager.GetString("FileCantOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game List.
        /// </summary>
        public static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game List(Web).
        /// </summary>
        public static string GameListWeb {
            get {
                return ResourceManager.GetString("GameListWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameWindow Resolution Change.
        /// </summary>
        public static string GameWindowResChange {
            get {
                return ResourceManager.GetString("GameWindowResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        public static string GenreAllComboBoxItem {
            get {
                return ResourceManager.GetString("GenreAllComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationFile(exe,text,png etc).
        /// </summary>
        public static string GenreApplication {
            get {
                return ResourceManager.GetString("GenreApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXE Files.
        /// </summary>
        public static string GenreExeExtension {
            get {
                return ResourceManager.GetString("GenreExeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebGame.
        /// </summary>
        public static string GenreWebGame {
            get {
                return ResourceManager.GetString("GenreWebGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSaver.
        /// </summary>
        public static string GenreWebSaver {
            get {
                return ResourceManager.GetString("GenreWebSaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website(https:/, http:/).
        /// </summary>
        public static string GenreWebsite {
            get {
                return ResourceManager.GetString("GenreWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string GenreWebsiteExtension {
            get {
                return ResourceManager.GetString("GenreWebsiteExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginHistory.
        /// </summary>
        public static string LoginHistory {
            get {
                return ResourceManager.GetString("LoginHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Resolution Change.
        /// </summary>
        public static string MainWindowResChange {
            get {
                return ResourceManager.GetString("MainWindowResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        public static string MemoCtxHeader {
            get {
                return ResourceManager.GetString("MemoCtxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo Resolution Change.
        /// </summary>
        public static string MemoWindowResChange {
            get {
                return ResourceManager.GetString("MemoWindowResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultipleLaunch.
        /// </summary>
        public static string MultipleLaunchText {
            get {
                return ResourceManager.GetString("MultipleLaunchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input name.
        /// </summary>
        public static string NameInput {
            get {
                return ResourceManager.GetString("NameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the appropriate web address.
        /// </summary>
        public static string NotContainsHttpError {
            get {
                return ResourceManager.GetString("NotContainsHttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected.
        /// </summary>
        public static string NotSelectFileError {
            get {
                return ResourceManager.GetString("NotSelectFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Genre.
        /// </summary>
        public static string PleaseSelectGenre {
            get {
                return ResourceManager.GetString("PleaseSelectGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input URL.
        /// </summary>
        public static string PleaseURL {
            get {
                return ResourceManager.GetString("PleaseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string PropertyCtxHeader {
            get {
                return ResourceManager.GetString("PropertyCtxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file (have you selected a file with no extension?).
        /// </summary>
        public static string SelectFileErrorMessage {
            get {
                return ResourceManager.GetString("SelectFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string SelectFileLabel {
            get {
                return ResourceManager.GetString("SelectFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Genre.
        /// </summary>
        public static string SelectGenreError {
            get {
                return ResourceManager.GetString("SelectGenreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingPage Resolution Change.
        /// </summary>
        public static string SettingResChange {
            get {
                return ResourceManager.GetString("SettingResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebAddress.
        /// </summary>
        public static string SimpleAddress {
            get {
                return ResourceManager.GetString("SimpleAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppData.
        /// </summary>
        public static string SimpleAppData {
            get {
                return ResourceManager.GetString("SimpleAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string SimpleBack {
            get {
                return ResourceManager.GetString("SimpleBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complated.
        /// </summary>
        public static string SimpleCompleted {
            get {
                return ResourceManager.GetString("SimpleCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlMenu.
        /// </summary>
        public static string SimpleControlMenu {
            get {
                return ResourceManager.GetString("SimpleControlMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string SimpleEnglish {
            get {
                return ResourceManager.GetString("SimpleEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXE PATH.
        /// </summary>
        public static string SimpleExePathLabel {
            get {
                return ResourceManager.GetString("SimpleExePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string SimpleExit {
            get {
                return ResourceManager.GetString("SimpleExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string SimpleExport {
            get {
                return ResourceManager.GetString("SimpleExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found,Please check exe path for property.
        /// </summary>
        public static string SimpleFileNotFound {
            get {
                return ResourceManager.GetString("SimpleFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string SimpleFontSize {
            get {
                return ResourceManager.GetString("SimpleFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string SimpleForward {
            get {
                return ResourceManager.GetString("SimpleForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullScreen.
        /// </summary>
        public static string SimpleFullScreen {
            get {
                return ResourceManager.GetString("SimpleFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SimpleGeneral {
            get {
                return ResourceManager.GetString("SimpleGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string SimpleImport {
            get {
                return ResourceManager.GetString("SimpleImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string SimpleJapanese {
            get {
                return ResourceManager.GetString("SimpleJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SimpleLanguage {
            get {
                return ResourceManager.GetString("SimpleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string SimpleMute {
            get {
                return ResourceManager.GetString("SimpleMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute(Disable).
        /// </summary>
        public static string SimpleMuteDisable {
            get {
                return ResourceManager.GetString("SimpleMuteDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute(Enable).
        /// </summary>
        public static string SimpleMuteEnable {
            get {
                return ResourceManager.GetString("SimpleMuteEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SimpleName {
            get {
                return ResourceManager.GetString("SimpleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string SimpleReload {
            get {
                return ResourceManager.GetString("SimpleReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string SimpleRes {
            get {
                return ResourceManager.GetString("SimpleRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution Change.
        /// </summary>
        public static string SimpleResChange {
            get {
                return ResourceManager.GetString("SimpleResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SimpleSave {
            get {
                return ResourceManager.GetString("SimpleSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string SimpleSetting {
            get {
                return ResourceManager.GetString("SimpleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using webview.
        /// </summary>
        public static string SimpleUseWebview {
            get {
                return ResourceManager.GetString("SimpleUseWebview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string SimpleVolume {
            get {
                return ResourceManager.GetString("SimpleVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video/Graphic/display.
        /// </summary>
        public static string VideoGraphics {
            get {
                return ResourceManager.GetString("VideoGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSaver.
        /// </summary>
        public static string WebSaver {
            get {
                return ResourceManager.GetString("WebSaver", resourceCulture);
            }
        }
    }
}
