//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuLauncher.LangString {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YuLauncher.LangString.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ApplicationLog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppLogButton {
            get {
                return ResourceManager.GetString("AppLogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteGame {
            get {
                return ResourceManager.GetString("DeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to edit mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditModeButton {
            get {
                return ResourceManager.GetString("EditModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Pick FilePath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrPickPath {
            get {
                return ResourceManager.GetString("ErrPickPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extension:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExtensionLabel {
            get {
                return ResourceManager.GetString("ExtensionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FavGames に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FavoriteGame {
            get {
                return ResourceManager.GetString("FavoriteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file type is cant open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileCantOpen {
            get {
                return ResourceManager.GetString("FileCantOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game List(Web) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameListWeb {
            get {
                return ResourceManager.GetString("GameListWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GameWindow Resolution Change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GameWindowResChange {
            get {
                return ResourceManager.GetString("GameWindowResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ALL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenreAllComboBoxItem {
            get {
                return ResourceManager.GetString("GenreAllComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ApplicationFile(exe,text,png etc) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenreApplication {
            get {
                return ResourceManager.GetString("GenreApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EXE Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenreExeExtension {
            get {
                return ResourceManager.GetString("GenreExeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WebGame に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenreWebGame {
            get {
                return ResourceManager.GetString("GenreWebGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WebSaver に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenreWebSaver {
            get {
                return ResourceManager.GetString("GenreWebSaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Website(https:/, http:/) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenreWebsite {
            get {
                return ResourceManager.GetString("GenreWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenreWebsiteExtension {
            get {
                return ResourceManager.GetString("GenreWebsiteExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LoginHistory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginHistory {
            get {
                return ResourceManager.GetString("LoginHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Menu Resolution Change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindowResChange {
            get {
                return ResourceManager.GetString("MainWindowResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MemoCtxHeader {
            get {
                return ResourceManager.GetString("MemoCtxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo Resolution Change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MemoWindowResChange {
            get {
                return ResourceManager.GetString("MemoWindowResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MultipleLaunch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MultipleLaunchText {
            get {
                return ResourceManager.GetString("MultipleLaunchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NameInput {
            get {
                return ResourceManager.GetString("NameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the appropriate web address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotContainsHttpError {
            get {
                return ResourceManager.GetString("NotContainsHttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotSelectFileError {
            get {
                return ResourceManager.GetString("NotSelectFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Select Genre に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseSelectGenre {
            get {
                return ResourceManager.GetString("PleaseSelectGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseURL {
            get {
                return ResourceManager.GetString("PleaseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PropertyCtxHeader {
            get {
                return ResourceManager.GetString("PropertyCtxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a file (have you selected a file with no extension?) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFileErrorMessage {
            get {
                return ResourceManager.GetString("SelectFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFileLabel {
            get {
                return ResourceManager.GetString("SelectFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Select Genre に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectGenreError {
            get {
                return ResourceManager.GetString("SelectGenreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SettingPage Resolution Change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingResChange {
            get {
                return ResourceManager.GetString("SettingResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WebAddress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleAddress {
            get {
                return ResourceManager.GetString("SimpleAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleBack {
            get {
                return ResourceManager.GetString("SimpleBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ControlMenu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleControlMenu {
            get {
                return ResourceManager.GetString("SimpleControlMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleEnglish {
            get {
                return ResourceManager.GetString("SimpleEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EXE PATH に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleExePathLabel {
            get {
                return ResourceManager.GetString("SimpleExePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleExit {
            get {
                return ResourceManager.GetString("SimpleExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Not Found,Please check exe path for property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleFileNotFound {
            get {
                return ResourceManager.GetString("SimpleFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleFontSize {
            get {
                return ResourceManager.GetString("SimpleFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleForward {
            get {
                return ResourceManager.GetString("SimpleForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FullScreen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleFullScreen {
            get {
                return ResourceManager.GetString("SimpleFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleJapanese {
            get {
                return ResourceManager.GetString("SimpleJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleLanguage {
            get {
                return ResourceManager.GetString("SimpleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleMute {
            get {
                return ResourceManager.GetString("SimpleMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute(Disable) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleMuteDisable {
            get {
                return ResourceManager.GetString("SimpleMuteDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute(Enable) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleMuteEnable {
            get {
                return ResourceManager.GetString("SimpleMuteEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleName {
            get {
                return ResourceManager.GetString("SimpleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleReload {
            get {
                return ResourceManager.GetString("SimpleReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resolution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleRes {
            get {
                return ResourceManager.GetString("SimpleRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resolution Change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleResChange {
            get {
                return ResourceManager.GetString("SimpleResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleSave {
            get {
                return ResourceManager.GetString("SimpleSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleSetting {
            get {
                return ResourceManager.GetString("SimpleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Using webview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SimpleUseWebview {
            get {
                return ResourceManager.GetString("SimpleUseWebview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WebSaver に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebSaver {
            get {
                return ResourceManager.GetString("WebSaver", resourceCulture);
            }
        }
    }
}
