//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuLauncher.LangString {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YuLauncher.LangString.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteGame {
            get {
                return ResourceManager.GetString("DeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Pick FilePath.
        /// </summary>
        public static string ErrPickPath {
            get {
                return ResourceManager.GetString("ErrPickPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension: .
        /// </summary>
        public static string ExtensionLabel {
            get {
                return ResourceManager.GetString("ExtensionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FavGames.
        /// </summary>
        public static string FavoriteGame {
            get {
                return ResourceManager.GetString("FavoriteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game List.
        /// </summary>
        public static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game List(R18).
        /// </summary>
        public static string GameList18 {
            get {
                return ResourceManager.GetString("GameList18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameWindow Resolution Change.
        /// </summary>
        public static string GameWindowResChange {
            get {
                return ResourceManager.GetString("GameWindowResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationFile(exe,text,png etc).
        /// </summary>
        public static string GenreApplication {
            get {
                return ResourceManager.GetString("GenreApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website(https:/, http:/).
        /// </summary>
        public static string GenreWebsite {
            get {
                return ResourceManager.GetString("GenreWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginHistory.
        /// </summary>
        public static string LoginHistory {
            get {
                return ResourceManager.GetString("LoginHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Resolution Change.
        /// </summary>
        public static string MainWindowResChange {
            get {
                return ResourceManager.GetString("MainWindowResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input name.
        /// </summary>
        public static string NameInput {
            get {
                return ResourceManager.GetString("NameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected.
        /// </summary>
        public static string NotSelectFileError {
            get {
                return ResourceManager.GetString("NotSelectFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Genre.
        /// </summary>
        public static string PleaseSelectGenre {
            get {
                return ResourceManager.GetString("PleaseSelectGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input URL.
        /// </summary>
        public static string PleaseURL {
            get {
                return ResourceManager.GetString("PleaseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file (have you selected a file with no extension?).
        /// </summary>
        public static string SelectFileErrorMessage {
            get {
                return ResourceManager.GetString("SelectFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string SelectFileLabel {
            get {
                return ResourceManager.GetString("SelectFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Genre.
        /// </summary>
        public static string SelectGenreError {
            get {
                return ResourceManager.GetString("SelectGenreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingPage Resolution Change.
        /// </summary>
        public static string SettingResChange {
            get {
                return ResourceManager.GetString("SettingResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string SimpleEnglish {
            get {
                return ResourceManager.GetString("SimpleEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string SimpleExit {
            get {
                return ResourceManager.GetString("SimpleExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullScreen.
        /// </summary>
        public static string SimpleFullScreen {
            get {
                return ResourceManager.GetString("SimpleFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string SimpleJapanese {
            get {
                return ResourceManager.GetString("SimpleJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SimpleLanguage {
            get {
                return ResourceManager.GetString("SimpleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution Change.
        /// </summary>
        public static string SimpleResChange {
            get {
                return ResourceManager.GetString("SimpleResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SimpleSave {
            get {
                return ResourceManager.GetString("SimpleSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string SimpleSetting {
            get {
                return ResourceManager.GetString("SimpleSetting", resourceCulture);
            }
        }
    }
}
