//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuLauncher.LangString {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language_ja_JP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_ja_JP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YuLauncher.LangString.Language.ja-JP", typeof(Language_ja_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加.
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アプリケーションログ.
        /// </summary>
        public static string AppLogButton {
            get {
                return ResourceManager.GetString("AppLogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string DeleteGame {
            get {
                return ResourceManager.GetString("DeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エディットモードにする.
        /// </summary>
        public static string EditModeButton {
            get {
                return ResourceManager.GetString("EditModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルパスを選択してください.
        /// </summary>
        public static string ErrPickPath {
            get {
                return ResourceManager.GetString("ErrPickPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拡張子: .
        /// </summary>
        public static string ExtensionLabel {
            get {
                return ResourceManager.GetString("ExtensionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お気に入りゲーム.
        /// </summary>
        public static string FavoriteGame {
            get {
                return ResourceManager.GetString("FavoriteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このファイルは開けません.
        /// </summary>
        public static string FileCantOpen {
            get {
                return ResourceManager.GetString("FileCantOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲーム一覧.
        /// </summary>
        public static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲーム一覧(Web).
        /// </summary>
        public static string GameListWeb {
            get {
                return ResourceManager.GetString("GameListWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲーム画面の解像度変更.
        /// </summary>
        public static string GameWindowResChange {
            get {
                return ResourceManager.GetString("GameWindowResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべて.
        /// </summary>
        public static string GenreAllComboBoxItem {
            get {
                return ResourceManager.GetString("GenreAllComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アプリケーションファイル(exe,text,png etc).
        /// </summary>
        public static string GenreApplication {
            get {
                return ResourceManager.GetString("GenreApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXE ファイル.
        /// </summary>
        public static string GenreExeExtension {
            get {
                return ResourceManager.GetString("GenreExeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウェブゲーム.
        /// </summary>
        public static string GenreWebGame {
            get {
                return ResourceManager.GetString("GenreWebGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サイト保存.
        /// </summary>
        public static string GenreWebSaver {
            get {
                return ResourceManager.GetString("GenreWebSaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウェブサイト(https:/, http:/).
        /// </summary>
        public static string GenreWebsite {
            get {
                return ResourceManager.GetString("GenreWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウェブ.
        /// </summary>
        public static string GenreWebsiteExtension {
            get {
                return ResourceManager.GetString("GenreWebsiteExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン履歴.
        /// </summary>
        public static string LoginHistory {
            get {
                return ResourceManager.GetString("LoginHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メニューの解像度変更.
        /// </summary>
        public static string MainWindowResChange {
            get {
                return ResourceManager.GetString("MainWindowResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メモ.
        /// </summary>
        public static string MemoCtxHeader {
            get {
                return ResourceManager.GetString("MemoCtxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メモの解像度変更.
        /// </summary>
        public static string MemoWindowResChange {
            get {
                return ResourceManager.GetString("MemoWindowResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複数起動.
        /// </summary>
        public static string MultipleLaunchText {
            get {
                return ResourceManager.GetString("MultipleLaunchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前を入力してください.
        /// </summary>
        public static string NameInput {
            get {
                return ResourceManager.GetString("NameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 適切なウェブアドレスを入力してください.
        /// </summary>
        public static string NotContainsHttpError {
            get {
                return ResourceManager.GetString("NotContainsHttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 何も選択されていません.
        /// </summary>
        public static string NotSelectFileError {
            get {
                return ResourceManager.GetString("NotSelectFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 種類を選択してください.
        /// </summary>
        public static string PleaseSelectGenre {
            get {
                return ResourceManager.GetString("PleaseSelectGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLを入力してください.
        /// </summary>
        public static string PleaseURL {
            get {
                return ResourceManager.GetString("PleaseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロパティ.
        /// </summary>
        public static string PropertyCtxHeader {
            get {
                return ResourceManager.GetString("PropertyCtxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルを選択してください(拡張子がないファイルを選択していませんか？).
        /// </summary>
        public static string SelectFileErrorMessage {
            get {
                return ResourceManager.GetString("SelectFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルを選択.
        /// </summary>
        public static string SelectFileLabel {
            get {
                return ResourceManager.GetString("SelectFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジャンルを選択してください.
        /// </summary>
        public static string SelectGenreError {
            get {
                return ResourceManager.GetString("SelectGenreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定画面の解像度変更.
        /// </summary>
        public static string SettingResChange {
            get {
                return ResourceManager.GetString("SettingResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウェブアドレス.
        /// </summary>
        public static string SimpleAddress {
            get {
                return ResourceManager.GetString("SimpleAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻る.
        /// </summary>
        public static string SimpleBack {
            get {
                return ResourceManager.GetString("SimpleBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コントロールメニュー.
        /// </summary>
        public static string SimpleControlMenu {
            get {
                return ResourceManager.GetString("SimpleControlMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英語
        ///.
        /// </summary>
        public static string SimpleEnglish {
            get {
                return ResourceManager.GetString("SimpleEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 実行アプリケーション場所.
        /// </summary>
        public static string SimpleExePathLabel {
            get {
                return ResourceManager.GetString("SimpleExePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了.
        /// </summary>
        public static string SimpleExit {
            get {
                return ResourceManager.GetString("SimpleExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルが見つかりません、プロパティーの実行アプリケーション場所を確認してください.
        /// </summary>
        public static string SimpleFileNotFound {
            get {
                return ResourceManager.GetString("SimpleFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォントサイズ
        ///.
        /// </summary>
        public static string SimpleFontSize {
            get {
                return ResourceManager.GetString("SimpleFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 進む.
        /// </summary>
        public static string SimpleForward {
            get {
                return ResourceManager.GetString("SimpleForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フルスクリーン.
        /// </summary>
        public static string SimpleFullScreen {
            get {
                return ResourceManager.GetString("SimpleFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語
        ///.
        /// </summary>
        public static string SimpleJapanese {
            get {
                return ResourceManager.GetString("SimpleJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 言語.
        /// </summary>
        public static string SimpleLanguage {
            get {
                return ResourceManager.GetString("SimpleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前.
        /// </summary>
        public static string SimpleName {
            get {
                return ResourceManager.GetString("SimpleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リロード.
        /// </summary>
        public static string SimpleReload {
            get {
                return ResourceManager.GetString("SimpleReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解像度.
        /// </summary>
        public static string SimpleRes {
            get {
                return ResourceManager.GetString("SimpleRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解像度変更
        ///.
        /// </summary>
        public static string SimpleResChange {
            get {
                return ResourceManager.GetString("SimpleResChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セーブ.
        /// </summary>
        public static string SimpleSave {
            get {
                return ResourceManager.GetString("SimpleSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        public static string SimpleSetting {
            get {
                return ResourceManager.GetString("SimpleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウェブビューを使う.
        /// </summary>
        public static string SimpleUseWebview {
            get {
                return ResourceManager.GetString("SimpleUseWebview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サイト保存.
        /// </summary>
        public static string WebSaver {
            get {
                return ResourceManager.GetString("WebSaver", resourceCulture);
            }
        }
    }
}
