name: Deploy to GitHub Releases

on:
  push:
    branches:
      - main

jobs:
  deploy-to-github-releases:
    runs-on: windows-latest
    steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Get Version from Project File
              id: get-version
              shell: bash
              run: echo "version=$(grep -oE '<Version>[^<]+' YuLauncher/YuLauncher.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT

            - name: Get Now Time
              id: get-time
              shell: bash
              run: echo "time=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

            - name: Install .NET
              uses: actions/setup-dotnet@v4
              with:
                    dotnet-version: 8.0.x


            - name: Publish Application
              run: dotnet publish YuLauncher/YuLauncher.csproj -c Release -o publish -r win-x64 --self-contained true

            - name: Create Velopack Release
              run: |
                    dotnet tool install -g vpk
                    vpk download github --repoUrl https://github.com/johmaru/Yu_Launcher
                    vpk pack --mainExe YuLauncher.exe -v ${{ steps.get-version.outputs.version }} -p publish --packId YuLauncher-${{ steps.get-version.outputs.version }}-${{ steps.get-time.outputs.time }}
                    vpk upload github --token ${{ secrets.TOKEN }}  --repoUrl https://github.com/johmaru/Yu_Launcher --publish --releaseName "YuLauncher ${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }}
